apiVersion: batch/v1
kind: Job
metadata:
  name: push-batch
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      name: push
    spec:
      containers:
        - name: push
          image: gcr.io/personal-webite-241414/push:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8Gi"
              cpu: "3"
      restartPolicy: OnFailure
