apiVersion: batch/v1
kind: Job
metadata:
  name: push-batch
spec:
  completions: 1
#  parallelism: 1
  template:
    metadata:
      name: push
    spec:
      containers:
        - name: push
          image: gcr.io/personal-webite-241414/push:latest
          imagePullPolicy: Always
      restartPolicy: OnFailure
      resources:
        requests:
          memory: "4Gi"
          cpu: "3"
