apiVersion: batch/v1
kind: Job
metadata:
  name: push-batch
spec:
  completions: 3
  parallelism: 3
  template:
    metadata:
      name: push
    spec:
      containers:
        - name: push-container
          image: push
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
